# # Auth Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pfemaroc-auth-deployment
#   labels:
#     app: pfemaroc-auth
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pfemaroc-auth
#   template:
#     metadata:
#       labels:
#         app: pfemaroc-auth
#     spec:
#       containers:
#       - name: pfemaroc-auth-container
#         image: yassinom/pfe_maroc_archive:auth
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 5050
#         env:
#         - name: MYSQL_HOST
#           value: pfemaroc-mysql-service
#         - name: MYSQL_ROOT_PASSWORD
#           value: "2002"
#         - name: MYSQL_DATABASE
#           value: "authDB"
#         - name: MYSQL_USER
#           value: "mehdi"
#         - name: MYSQL_PASSWORD
#           value: "2002"



# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-auth-deployment
  labels:
    app: pfemaroc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-auth
  template:
    metadata:
      labels:
        app: pfemaroc-auth
    spec:
      imagePullSecrets:
      - name: docker-cred  
      containers:
      - name: pfe-maroc-auth-container
        image: yassinom/pfe_maroc_archive:auth
        imagePullPolicy: Always  # mandatory, always pull the latest image
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: pfemaroc-mysql-service









# MySQL Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-mysql-deployment
  labels:
    app: pfemaroc-auth-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-auth-mysql
  template:
    metadata:
      labels:
        app: pfemaroc-auth-mysql
    spec:
      containers:
      - name: pfemaroc-auth-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"


# Auth Service with NodePort (External Access)
---
apiVersion: v1
kind: Service
metadata:
  name: pfemaroc-auth-service
spec:
  type: NodePort
  selector:
    app: pfemaroc-auth
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 30005  # Accessible on port 30005 on all nodes


# MySQL Service
---
apiVersion: v1
kind: Service
metadata:
  name: pfemaroc-mysql-service
spec:
  clusterIP: None
  selector:
    app: pfemaroc-auth-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306






# # MySQL Deployment 2
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pfemaroc-mysql-deployment2
#   labels:
#     app: pfemaroc-auth-mysql2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pfemaroc-auth-mysql2
#   template:
#     metadata:
#       labels:
#         app: pfemaroc-auth-mysql2
#     spec:
#       containers:
#       - name: pfemaroc-auth-mysql2
#         image: mysql:latest
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "2002"
#         - name: MYSQL_DATABASE
#           value: "authDB"
#         - name: MYSQL_USER
#           value: "mehdi"
#         - name: MYSQL_PASSWORD
#           value: "2002"



# # MySQL Service 2
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pfemaroc-mysql-service2
# spec:
#   clusterIP: None
#   selector:
#     app: pfemaroc-auth-mysql2
#   ports:
#   - protocol: TCP
#     port: 3306
#     targetPort: 3306


