apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-maroc-deployment
  labels:
    app: pfe-maroc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-maroc
  template:
    metadata:
      labels:
        app: pfe-maroc
    spec:
      imagePullSecrets:
      - name: docker-cred  
      containers:
      - name: pfe-maroc-container
        image: yassinom/pfe_maroc_archive:auth
        ports:
        - containerPort: 5050
          hostPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: pfe-maroc-service
spec:
  selector:
    app: pfe-maroc
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
