# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pfe-maroc-deployment
#   labels:
#     app: pfe-maroc
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pfe-maroc
#   template:
#     metadata:
#       labels:
#         app: pfe-maroc
#     spec:
#       imagePullSecrets:
#       - name: docker-cred  
#       containers:
#       - name: pfe-maroc-container
#         image: yassinom/pfe_maroc_archive:auth
#         ports:
#         - containerPort: 5050
#           hostPort: 5050

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pfe-maroc-service
# spec:
#   selector:
#     app: pfe-maroc
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 5050
#     targetPort: 5050






















# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-maroc-auth-deployment
  labels:
    app: pfe-maroc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-maroc-auth
  template:
    metadata:
      labels:
        app: pfe-maroc-auth
    spec:
      imagePullSecrets:
      - name: docker-cred  
      containers:
      - name: pfe-maroc-auth-container
        image: yassinom/pfe_maroc_archive:auth
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: pfe-maroc-mysql-service

# MySQL Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-maroc-mysql-deployment
  labels:
    app: pfe-maroc-auth-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-maroc-auth-mysql
  template:
    metadata:
      labels:
        app: pfe-maroc-auth-mysql
    spec:
      containers:
      - name: pfe-maroc-auth-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"

# # Auth Service
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pfe-maroc-auth-service
# spec:
#   selector:
#     app: pfe-maroc-auth
#   type: ClusterIP
#   ports:
#   - protocol: TCP
#     port: 5050
#     targetPort: 5050

# Auth Service (Headless)
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-maroc-auth-service
spec:
  clusterIP: None
  selector:
    app: pfe-maroc-auth
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050



# MySQL Service
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-maroc-mysql-service
spec:
  clusterIP: None
  selector:
    app: pfe-maroc-auth-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306





# MySQL Deployment 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-maroc-mysql-deployment2
  labels:
    app: pfe-maroc-auth-mysql2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-maroc-auth-mysql2
  template:
    metadata:
      labels:
        app: pfe-maroc-auth-mysql2
    spec:
      containers:
      - name: pfe-maroc-auth-mysql2
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"



# MySQL Service 2
---
apiVersion: v1
kind: Service
metadata:
  name: pfe-maroc-mysql-service2
spec:
  clusterIP: None
  selector:
    app: pfe-maroc-auth-mysql2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

























# # Auth and MySQL Combined Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pfe-maroc-combined-deployment
#   labels:
#     app: pfe-maroc-combined
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pfe-maroc-combined
#   template:
#     metadata:
#       labels:
#         app: pfe-maroc-combined
#     spec:
#       imagePullSecrets:
#       - name: docker-cred  
#       containers:
#       - name: pfe-maroc-auth-container
#         image: yassinom/pfe_maroc_archive:auth
#         ports:
#         - containerPort: 5050
#         env:
#         - name: MYSQL_HOST
#           value: pfe-maroc-auth-service
#         - name: MYSQL_DATABASE
#           value: "authDB"
#         - name: MYSQL_USER
#           value: "mehdi"
#         - name: MYSQL_PASSWORD
#           value: "2002"
#       - name: pfe-maroc-auth-mysql-container
#         image: mysql:latest
#         ports:
#         - containerPort: 3306
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "2002"
#         - name: MYSQL_DATABASE
#           value: "authDB"
#         - name: MYSQL_USER
#           value: "mehdi"
#         - name: MYSQL_PASSWORD
#           value: "2002"

# # Auth Service
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: pfe-maroc-auth-service
# spec:
#   selector:
#     app: pfe-maroc-combined
#   type: LoadBalancer
#   ports:
#   - protocol: TCP
#     port: 5050
#     targetPort: 5050
