# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PFEMaroc-auth-deployment
  labels:
    app: PFEMaroc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PFEMaroc-auth
  template:
    metadata:
      labels:
        app: PFEMaroc-auth
    spec:
      imagePullSecrets:
      - name: docker-cred  
      containers:
      - name: PFEMaroc-auth-container
        image: yassinom/pfe_maroc_archive:auth
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: PFEMaroc-mysql-service

# MySQL Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PFEMaroc-mysql-deployment
  labels:
    app: PFEMaroc-auth-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PFEMaroc-auth-mysql
  template:
    metadata:
      labels:
        app: PFEMaroc-auth-mysql
    spec:
      containers:
      - name: PFEMaroc-auth-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"


# Auth Service (Headless)
---
apiVersion: v1
kind: Service
metadata:
  name: PFEMaroc-auth-service
spec:
  clusterIP: None
  selector:
    app: PFEMaroc-auth
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050



# MySQL Service
---
apiVersion: v1
kind: Service
metadata:
  name: PFEMaroc-mysql-service
spec:
  clusterIP: None
  selector:
    app: PFEMaroc-auth-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306





# MySQL Deployment 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PFEMaroc-mysql-deployment2
  labels:
    app: PFEMaroc-auth-mysql2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PFEMaroc-auth-mysql2
  template:
    metadata:
      labels:
        app: PFEMaroc-auth-mysql2
    spec:
      containers:
      - name: PFEMaroc-auth-mysql2
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"



# MySQL Service 2
---
apiVersion: v1
kind: Service
metadata:
  name: PFEMaroc-mysql-service2
spec:
  clusterIP: None
  selector:
    app: PFEMaroc-auth-mysql2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306


