# PeerAuthentication for STRICT mTLS mode
# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: default
# spec:
#   mtls:
#     mode: STRICTs


# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-auth-deployment
  labels:
    app: pfemaroc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-auth
  template:
    metadata:
      labels:
        app: pfemaroc-auth
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: pfemaroc-auth-container
        image: yassinom/pfe_maroc_archive:service_auth
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_HOST
          value: pfemaroc-auth-mysql-service
        - name: MYSQL_DATABASE
          value: "authDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"

---

# Project Deployment  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-project-deployment
  labels:
    app: pfemaroc-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-project
  template:
    metadata:
      labels:
        app: pfemaroc-project
    spec:
      imagePullSecrets:
      - name: docker-cred  
      containers:
      - name: pfemaroc-project-container
        image: yassinom/pfe_maroc_archive:service_project
        imagePullPolicy: Always
        ports:
        - containerPort: 6060
        env:
        - name: MYSQL_HOST
          value: pfemaroc-project-mysql-service
        - name: MYSQL_DATABASE
          value: "projectDB"
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: pfemaroc-frontend-deployment
  labels:
    app: pfemaroc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-frontend
  template:
    metadata:
      labels:
        app: pfemaroc-frontend
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: pfemaroc-frontend-container
        image: yassinom/pfe_maroc_archive:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---        

# Auth MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-auth-mysql-deployment
  labels:
    app: pfemaroc-auth-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-auth-mysql
  template:
    metadata:
      labels:
        app: pfemaroc-auth-mysql
    spec:
      containers:
      - name: pfemaroc-auth-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "authDB" 
        - name: MYSQL_USER
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"

---

# Project MySQL Deployment  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfemaroc-project-mysql-deployment
  labels:
    app: pfemaroc-project-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfemaroc-project-mysql
  template:
    metadata:
      labels:
        app: pfemaroc-project-mysql
    spec:
      containers:
      - name: pfemaroc-project-mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2002"
        - name: MYSQL_DATABASE
          value: "projectDB"
        - name: MYSQL_USER  
          value: "mehdi"
        - name: MYSQL_PASSWORD
          value: "2002"

---

# Auth Service  
apiVersion: v1
kind: Service
metadata:
  name: pfemaroc-auth-service 
spec:
  selector:
    app: pfemaroc-auth
  ports:
  - protocol: TCP 
    port: 5050
    targetPort: 5050

---  

# Project Service
apiVersion: v1  
kind: Service
metadata:
  name: pfemaroc-project-service
spec:
  selector:  
    app: pfemaroc-project
  ports:
  - protocol: TCP
    port: 6060  
    targetPort: 6060

---

# Frontend Service (NodePort for External Access)
apiVersion: v1
kind: Service
metadata:
  name: pfemaroc-frontend-service
spec:
  type: NodePort
  selector:
    app: pfemaroc-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30007
     
---

# Auth MySQL Service  
apiVersion: v1
kind: Service 
metadata:
  name: pfemaroc-auth-mysql-service
spec:
  clusterIP: None
  selector:
    app: pfemaroc-auth-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
       
---

# Project MySQL Service
apiVersion: v1
kind: Service
metadata: 
  name: pfemaroc-project-mysql-service  
spec:
  clusterIP: None
  selector:
    app: pfemaroc-project-mysql
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306
